server:
  port: 8282

# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:walletdb
    driverClassName: org.h2.Driver
    username: sa
    password:
